var lay_id = layer_get_id("Backgrounds_1")
var back_id = layer_background_get_id(lay_id)
var lay_id2 = layer_get_id("Backgrounds_2")
var back_id2 = layer_background_get_id(lay_id2)
var lay_id3 = layer_get_id("Backgrounds_3")
var back_id3 = layer_background_get_id(lay_id3)
if ((global.panic == 1) && (layer_background_get_sprite(back_id) == 1230))
    layer_background_sprite(back_id, 1229)
if ((global.panic == 1) && (layer_background_get_sprite(back_id) == 1227))
    layer_background_sprite(back_id, 1228)
if ((global.panic == 1) && (layer_background_get_sprite(back_id3) == 1232))
    layer_background_sprite(back_id3, 1233)
if ((global.panic == 1) && (layer_background_get_sprite(back_id) == 1196))
    layer_background_sprite(back_id, 1197)
if ((global.panic == 1) && (layer_background_get_sprite(back_id) == 1199))
    layer_background_sprite(back_id, 1200)
if ((global.panic == 1) && (layer_background_get_sprite(back_id2) == 1201))
    layer_background_sprite(back_id2, 1202)
if ((global.panic == 1) && (layer_background_get_sprite(back_id) == 1266))
    layer_background_sprite(back_id, 1267)
if ((global.panic == 1) && (layer_background_get_sprite(back_id2) == 1264))
    layer_background_sprite(back_id2, 1265)
if ((global.panic == 1) && (layer_background_get_sprite(back_id3) == 1262))
    layer_background_sprite(back_id3, 1263)

