/// @description funne messages
randommessage = choose(
	"PIZZA TOWER STORIES SPONGEMAN",
	"ARE THERE ENOUGH FORCED JOKES IN THIS MOD YET",
	"HOMERSTUCK",
	"FNF DISTRACTION FNF DISTRACTION",
	"FUCK BITCH SHIT COCK ASS DICK",
	"MORE FORCED JOKES",
	"PLAY THE TERRARIA CALAMITY MOD ITS SO GOOD",
	"REGULAR SHOW",
	"HOLY FUCKING SHIT",
	"ME PICAN LOS COCOOOOOOOOOO",
	"HOMER OVER SNICK",
	"TO KILL A CYBERDEMON SHOOT AT IT UNTIL IT DIES",
	"YOU'RE A POOPIE HEAD",
	"TRANS RIGHTS"
)
if oldrandommessage == randommessage
{
	alarm[1] = 1
}
else
{
	oldrandommessage = randommessage
	alarm[1] = 3600
}
